// given a set of geofence corners, assume a drone away form the geofence
// generate a local coordinate system for the geofence assuming the drones start point is the origin.
// Plot the points in plotters
mod geofence;
mod poisson_disk;
mod delaunay_triangulation;

use plotters::{prelude::*, style::full_palette::PURPLE};
use geofence::{local_coords, MIN_RAD, K};
use poisson_disk::bridson_algo;
use delaunay_triangulation::{triangulate};

pub fn main() -> Result<(), Box<dyn std::error::Error>> {
    let (min_x, min_y) = (-14.1333, -0.4452);
    let (max_x, max_y) = (6.0322, 40.1863);
    let bounding_box = vec![
        (min_x, min_y),
        (max_x, min_y),
        (max_x, max_y),
        (min_x, max_y),
        (min_x, min_y)
    ];

    let local_geofence = local_coords();
    let seeds = bridson_algo(local_geofence.clone(), MIN_RAD, K);
    // let formatted = seeds.iter().map(|(x, y)| format!("({:.2}, {:.2})", x, y)).collect::<Vec<String>>();

    let root = BitMapBackend::new("plotters-doc-data/delaunay_triangulation.png", (640, 480)).into_drawing_area(); // Create a drawing area with the specified size
    root.fill(&WHITE)?; // Fill the background with white color
    
    let mut chart = ChartBuilder::on(&root)
            .caption("Geofence", ("sans-serif", 50).into_font())
            .margin(20)
            .x_label_area_size(30)
            .y_label_area_size(30)
            .build_cartesian_2d(-15f64..15f64, -5f64..50f64)?; // Build a chart with the specified caption and margins
    // I need black lines for X and Y axes.
    chart.configure_mesh().axis_style(TRANSPARENT).x_desc("E (m)").y_desc("N (m)").draw()?; // Configure the mesh with axis descriptions and draw it
    
    // Bold X-axis at y=0
    chart.draw_series(LineSeries::new(
        vec![(-15.0, 0.0), (15.0, 0.0)], 
        BLACK.stroke_width(1)
    ))?;

    // Bold Y-axis at x=0
    chart.draw_series(LineSeries::new(
        vec![(0.0, -5.0), (0.0, 50.0)], 
        BLACK.stroke_width(1)
    ))?;

    // Plot the geofence as a closed polygon
    let mut fence = local_geofence.clone();
    fence.push(local_geofence[0]);
    chart.draw_series(LineSeries::new(
        fence.iter().map(|&(e, n)| (e as f64, n as f64)),
        BLUE.stroke_width(1)
    ))?;

    // Plot the geofence corners as points on the chart
    chart.draw_series(local_geofence.iter().map(|&(e, n)| {
        EmptyElement::at((e as f64, n as f64)) 
            + Circle::new((0, 0), 2, RED.filled())
            + Text::new(format!("({:.2}, {:.2})", e, n), (5, -15), ("sans-serif", 10).into_font())
    }))?;
    
    // Plot the bounding box as a closed polygon
    chart.draw_series(LineSeries::new(
        bounding_box.iter().map(|&(e, n)| (e as f64, n as f64)),   
        PURPLE.stroke_width(1)
    ))?;

    // Plot the seeds generated by Bridson's algorithm as points on the charts
    chart.draw_series(seeds.iter().map(|&(e, n)| {
        EmptyElement::at((e as f64, n as f64)) 
            + Circle::new((0, 0), 2, BLACK.filled())
    }))?;


    // Plot edges between seeds using Delaunay triangulation
    // add the local geofence points to the seeds for triangulation
    let mut all_points = seeds.clone();
    all_points.extend(local_geofence.clone());
    let mesh = triangulate(all_points);
    let edges = mesh.get_edges_for_plotting();
    chart.draw_series(
        edges.into_iter().map(|(org, dest)| {
            PathElement::new(
                [org, dest],
                BLACK.stroke_width(1),
            )
        })
    )?;
    
    chart.configure_series_labels().background_style(WHITE.mix(0.8)).border_style(&BLACK).draw()?; // Configure and draw the series labels with a background and border

    root.present()?;
    Ok(())

}